# Configuration for registering the GitHub App
# Visit https://github.com/settings/apps/new to create

name: DungeonCrawler Bot
description: Automates DungeonCrawlerAI repository workflows
url: https://github.com/Xaric23/DungeonCrawlerAI

# Public or internal
public: false

# Webhook settings
default_events:
  - issues
  - issue_comment
  - pull_request
  - pull_request_review
  - release
  - push

# Permissions needed
default_permissions:
  # Read access
  contents: read
  metadata: read
  
  # Write access
  issues: write
  pull_requests: write
  
# Where can this app be installed
# single - Only on the owner's account
# selected - On selected repositories
single_file_name: .github/dungeoncrawler-bot.yml
