# Configuration for registering the GitHub App
# Visit https://github.com/settings/apps/new to create

name: DungeonCrawler Bot
description: Automates DungeonCrawlerAI repository workflows
url: https://github.com/Xaric23/DungeonCrawlerAI

# Public or internal
public: false

# Webhook settings
default_events:
  - issues
  - issue_comment
  - pull_request
  - release

# Permissions needed
default_permissions:
  # Read access
  contents: read
  metadata: read
  
  # Write access
  issues: write
  pull_requests: write
  
# Path (within each repository) to this app's configuration file
# Used when the app relies on a single config file per repo
# e.g., .github/dungeoncrawler-bot.yml in the default branch
single_file_name: .github/dungeoncrawler-bot.yml
